name: Auto Label

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add labels to issues
      if: github.event_name == 'issues'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'hacktoberfest, hacktoberfest-accepted'

    - name: Add labels to pull requests
      if: github.event_name == 'pull_request'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'hacktoberfest, hacktoberfest-accepted'
