name: Auto Message and Star

on:
  issues:
    types: [opened]

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send welcome message
        run: |
          ISSUE_NUMBER=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          COMMENT_BODY=$(cat <<EOF
          Hi @${{ github.actor }}! Thanks for opening this issue. If you haven't already, please consider starring our repository to support us!
          <h1>Give us a star if you haven't yet</h1>
          <a class="github-button" href="https://github.com/allanoguis/coding-notes" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star allanoguis/coding-notes on GitHub">Star</a>
          <script async defer src="https://buttons.github.io/buttons.js"></script>
          EOF
          )
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" \
          -d "{\"body\": \"$COMMENT_BODY\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments"
